# Generated by Django 5.2 on 2026-02-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0004_challenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="full_name",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
